imports:
  - { resource: repositories.yaml }

services:
  _defaults:
    autowire: true

  Raid\Boss\Service\:
    resource: '../Service/'

  Raid\Boss\Repository\:
    resource: '../Repository/'

  Raid\Boss\Command\:
    resource: '../Command/'
