imports:
  - { resource: command-handlers.yaml }
  - { resource: repositories.yaml }

services:
  raid.player.service.search_player:
    class: Raid\Player\Service\SearchPlayerService
    arguments:
      - '@raid.player.repository.player'
