imports:
  - { resource: command-handlers.yaml }
services:
  raid.player.service.create_player:
    class: Raid\Player\Service\CreatePlayerService

  raid.player.service.search_player:
    class: Raid\Player\Service\SearchPlayerService
