services:
  _defaults:
    autowire: true

  Raid\Player\Command\:
    resource: '../Command/'

  Raid\Player\Service\:
    resource: '../Service/'

  Raid\Player\Repository\:
    resource: '../Repository/'
