imports:
  - { resource: ../src/Player/Resource/services.yaml }
  - { resource: ../src/Boss/Resource/services.yaml }

services:
  _defaults:
    autowire: true

  League\Tactician\Handler\MethodNameInflector\MethodNameInflector:
    class: League\Tactician\Handler\MethodNameInflector\HandleInflector

  League\Tactician\Handler\CommandNameExtractor\CommandNameExtractor:
    class: League\Tactician\Plugins\NamedCommand\NamedCommandExtractor

  League\Tactician\Handler\CommandHandlerMiddleware: ~

  League\Tactician\Handler\Locator\HandlerLocator:
    class: League\Tactician\Handler\Locator\InMemoryLocator
    # TODO compiler pass
    calls:
        - ['addHandler', ['@Raid\Player\Command\CreatePlayerHandler', 'create_new_player']]
        - ['addHandler', ['@Raid\Player\Command\Party\CreatePartyHandler', 'create_party']]
        - ['addHandler', ['@Raid\Boss\Command\StartRaidHandler', 'start_raid']]

  League\Tactician\CommandBus:
    public: true
    arguments: [['@League\Tactician\Handler\CommandHandlerMiddleware']]
