imports:
  - { resource: command-bus.yaml }

parameters:
  project_name: 'Raid'
services:
  _defaults:
    autowire: true

  Raid\App\Command\:
    resource: '../src/App/Command/'
    exclude: '../src/App/Command/ConsoleColorFormatter.php'
    tags: ['console.command']

  Symfony\Component\Console\Application:
    public: true
    arguments:
      - '%project_name%'
