imports:
  - { resource: command-bus.yaml }

parameters:
  project_name: 'Raid'
services:
  _defaults:
    autowire: true
    autoconfigure: true

  Raid\App\Command\:
    resource: '../src/App/Command/'

  application.console:
    public: true
    class: Symfony\Component\Console\Application
    arguments:
      - '%project_name%'
