imports:
  - { resource: ../src/App/Resource/commands.yaml }
  - { resource: command-bus.yaml }

parameters:
  project_name: 'Raid'
services:
  application.console:
    public: true
    class: Symfony\Component\Console\Application
    arguments:
      - '%project_name%'
